---
# file: tasks/use-apt.yml
#
# Configure mongodb from APT repository.
#
# @see http://wiki.mongodb.org/Install
# @see http://mongodb.org/packages/ubuntu/dists/
# @see http://mongodb.org/packages/debian/dists/
#

- name: install add-apt-repository binary for Ansible to work
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python-software-properties
    - apt-transport-https



- name: add MongoDB public GPG key
  apt_key: url=https://docs.mongodb.org/10gen-gpg-key.asc id=7F0CEB10 state=present validate_certs=False

- name: add MongoDB stable repository (for Ubuntu)
  apt_repository: repo='deb http://repo.mongodb.org/apt/{{ ansible_distribution|lower }}  {{ ansible_distribution_release|lower }}/mongodb-org/3.0 multiverse' state=present
  when: ansible_distribution == "Ubuntu"

- name: add MongoDB stable repository (for Debian)
  apt_repository: repo='deb http://repo.mongodb.org/apt/{{ ansible_distribution|lower }}  {{ ansible_distribution_release|lower }}/mongodb-org/3.0 main' state=present
  when: ansible_distribution == "Debian"

- name: run the equivalent of "apt-get update" as a separate step
  apt: update_cache=yes



- name: install MongoDB with specific version
  apt: name={{ item }}  update_cache=yes  state=present force=yes
  with_items:
    - "mongodb-org={{ mongodb_version }}*"
    - "mongodb-org-shell={{ mongodb_version }}*"
    - "mongodb-org-tools={{ mongodb_version }}*"
  when: mongodb_version is defined

- name: install MongoDB with default version
  apt: name={{ item }}  update_cache=yes  state=present force=yes
  with_items: [ "mongodb-org" ]
  when: mongodb_version is not defined



#
# INIT system for mongod
#

- name: set mongod INIT status and start
  service: name=mongod state=started enabled=yes
  when: '"mongod" in mongodb_components'

- name: unset mongod INIT status and stop, if necessary
  service: name=mongod state=stopped enabled=no
  ignore_errors: yes
  when: '"mongod" not in mongodb_components'


#
# INIT system for mongos
#

- name: copy mongos INIT script to server (Ubuntu)
  template: src="../templates/mongos.upstart.ubuntu.conf.j2"  dest="/etc/init/mongos.conf"
  when: '("mongos" in mongodb_components)  and  (ansible_distribution == "Ubuntu")'

- name: copy mongos INIT script to server (Debian)
  template: src="../templates/mongos.sysvinit.debian.sh.j2"  dest="/etc/init.d/mongos" mode="a+x"
  when: '("mongos" in mongodb_components)  and  (ansible_distribution == "Debian")'

- name: set mongos INIT status (SysV style)
  shell: update-rc.d mongos defaults
  when: '("mongos" in mongodb_components)  and  (ansible_distribution == "Debian")'

- name: set mongos INIT status
  service: name=mongos enabled=yes
  when: '"mongos" in mongodb_components'
